'use strict';

/**
 * Scorecard ledger — append-only event log + aggregation + leaderboard render.
 *
 * Mirrors the wr/memory/decisions.jsonl convention: one JSON object per line,
 * durable, diff-friendly, replayable. Each line is one scored PR (or one
 * remediation outcome). Aggregation is a pure replay over the events so the
 * leaderboard can always be regenerated from the ledger alone.
 */

const fs = require('fs');
const path = require('path');
const { updateTrust, grade, STARTING_TRUST } = require('./score-engine');
const { agentTrends, arrow } = require('./trends');

const LEDGER_PATH = path.join(__dirname, '../../wr/memory/agent-scorecard.jsonl');
const LEADERBOARD_PATH = path.join(__dirname, '../../docs/AGENT_SCORECARD.md');

function appendEvent(event, ledgerPath = LEDGER_PATH) {
  const line = JSON.stringify({ ts: new Date().toISOString().slice(0, 10), ...event });
  fs.mkdirSync(path.dirname(ledgerPath), { recursive: true });
  fs.appendFileSync(ledgerPath, line + '\n');
  return line;
}

function readEvents(ledgerPath = LEDGER_PATH) {
  if (!fs.existsSync(ledgerPath)) return [];
  return fs
    .readFileSync(ledgerPath, 'utf8')
    .split('\n')
    .filter(Boolean)
    .map((l) => {
      try {
        return JSON.parse(l);
      } catch {
        return null;
      }
    })
    .filter(Boolean);
}

/**
 * Replay events into a per-agent aggregate. Pure: takes events, returns a map.
 *
 * event shapes consumed:
 *   {type:'score', agent, pr, quality, hallucination:<count>, latencyMin}
 *   {type:'remediation', agent, pr, tier, recovered:<bool>}
 */
function aggregate(events = []) {
  const agents = new Map();

  const get = (name) => {
    if (!agents.has(name)) {
      agents.set(name, {
        agent: name,
        trust: STARTING_TRUST,
        prs: 0,
        hallucinationEvents: 0,
        remediations: 0,
        recoveries: 0,
        latencySumMin: 0,
        latencyCount: 0,
        lastPr: null,
        events: [], // retained in order for trend analysis
      });
    }
    return agents.get(name);
  };

  for (const ev of events) {
    if (!ev || !ev.agent) continue;
    const a = get(ev.agent);
    a.events.push(ev);

    if (ev.type === 'score') {
      a.prs += 1;
      a.trust = updateTrust(a.trust, Number(ev.quality) || 0);
      if (Number(ev.hallucination) > 0) a.hallucinationEvents += 1;
      if (typeof ev.latencyMin === 'number') {
        a.latencySumMin += ev.latencyMin;
        a.latencyCount += 1;
      }
      a.lastPr = ev.pr ?? a.lastPr;
    } else if (ev.type === 'remediation') {
      a.remediations += 1;
      if (ev.recovered) a.recoveries += 1;
    }
  }

  // Derive rates and longitudinal trends.
  for (const a of agents.values()) {
    a.hallucinationRate = a.prs ? +(a.hallucinationEvents / a.prs).toFixed(3) : 0;
    a.recoveryRate = a.remediations ? +(a.recoveries / a.remediations).toFixed(3) : null;
    a.avgLatencyMin = a.latencyCount ? Math.round(a.latencySumMin / a.latencyCount) : null;
    a.grade = grade(a.trust);
    a.trends = agentTrends(a.events);
  }

  return agents;
}

function renderLeaderboard(agents) {
  const rows = [...agents.values()].sort((x, y) => y.trust - x.trust);
  const fmtPct = (n) => (n == null ? '—' : `${Math.round(n * 100)}%`);
  const fmtLat = (n) => (n == null ? '—' : `${n}m`);

  const lines = [];
  lines.push('<!-- generated by scripts/agent-scorecard/ledger.js — do not edit by hand -->');
  lines.push('# Fleet Trust Scorecard');
  lines.push('');
  lines.push(
    'Per-agent trust derived from every PR they ship. Higher = more reliable. ' +
      'A low **recovery rate** is a signal that our *prompts/scripts* need work, ' +
      'not just the agent. Regenerated automatically from `wr/memory/agent-scorecard.jsonl`.'
  );
  lines.push('');
  lines.push('| Rank | Agent | Trust | Trend | Grade | PRs | Builds | Hallucination rate | Recovery rate | Avg latency |');
  lines.push('| ---: | --- | ---: | :---: | :---: | ---: | ---: | ---: | ---: | ---: |');
  rows.forEach((a, i) => {
    const t = a.trends || {};
    const trendArrow = t.quality ? arrow(t.quality.direction) : '·';
    const builds = `${t.builds || 0}${t.capabilitiesAdded ? ` (+${t.capabilitiesAdded})` : ''}`;
    lines.push(
      `| ${i + 1} | \`${a.agent}\` | ${a.trust} | ${trendArrow} | ${a.grade.letter} (${a.grade.label}) | ${a.prs} | ${builds} | ` +
        `${fmtPct(a.hallucinationRate)} | ${fmtPct(a.recoveryRate)} | ${fmtLat(a.avgLatencyMin)} |`
    );
  });
  if (!rows.length) {
    lines.push('| — | *no scored PRs yet* | — | — | — | — | — | — | — | — |');
  }
  lines.push('');
  lines.push('**Trend** = quality direction over recent PRs vs the prior window ' +
    '(↑ improving · ↓ regressing · → flat · `·` not enough data). ' +
    '**Builds** = `feat` PRs that shipped (`+N` = net-new files under skills/products/engines/workflows/scripts — capability you didn\'t have before).');

  // Per-dimension movement, so you can see *where* an agent is improving or slipping.
  const withTrends = rows.filter((a) => a.trends && (a.trends.improving.length || a.trends.regressing.length));
  if (withTrends.length) {
    lines.push('');
    lines.push('## Per-dimension movement');
    lines.push('');
    for (const a of withTrends) {
      const up = a.trends.improving.length ? `improving: ${a.trends.improving.join(', ')}` : '';
      const down = a.trends.regressing.length ? `regressing: ${a.trends.regressing.join(', ')}` : '';
      lines.push(`- \`${a.agent}\` — ${[up, down].filter(Boolean).join(' · ')}`);
    }
  }

  lines.push('');
  lines.push(`*Last updated: ${new Date().toISOString().slice(0, 10)}.*`);
  return lines.join('\n') + '\n';
}

function writeLeaderboard(agents, leaderboardPath = LEADERBOARD_PATH) {
  fs.mkdirSync(path.dirname(leaderboardPath), { recursive: true });
  fs.writeFileSync(leaderboardPath, renderLeaderboard(agents));
  return leaderboardPath;
}

module.exports = {
  LEDGER_PATH,
  LEADERBOARD_PATH,
  appendEvent,
  readEvents,
  aggregate,
  renderLeaderboard,
  writeLeaderboard,
};
