const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const { buildData } = require("../scripts/build-agent-creator-data.js");

test("buildData assembles the agent-creator catalog from the registries", () => {
  const data = buildData();
  assert.equal(data.schema_version, "1.0");
  assert.equal(data.repo, "midnghtsapphire/revvel-standards");

  assert.ok(data.skills.length >= 50, `expected >=50 skills, got ${data.skills.length}`);
  for (const s of data.skills) {
    assert.ok(s.name, "skill missing name");
    assert.ok(Array.isArray(s.triggers), `skill ${s.name} triggers not an array`);
    assert.ok(s.category, `skill ${s.name} missing category`);
  }

  const profileIds = data.profiles.map((p) => p.id);
  assert.ok(profileIds.includes("orchestrator"), "orchestrator profile missing");
  assert.ok(profileIds.includes("code_patch"), "code_patch profile missing");

  assert.ok(data.personas.length >= 5, "persona registry looks truncated");
  assert.ok(data.personas.every((p) => p.handle && p.name));

  assert.ok(data.prompt_templates.includes("triage"), "triage prompt template missing");
  assert.ok(Object.keys(data.label_triggers).length > 0, "label_triggers empty");
});

test("CLI writes both JSON and window-global artifacts", () => {
  const outDir = fs.mkdtempSync(path.join(os.tmpdir(), "agent-creator-"));
  const { execFileSync } = require("node:child_process");
  execFileSync(process.execPath, [
    path.join(__dirname, "..", "scripts", "build-agent-creator-data.js"),
    "--out-dir", outDir,
  ]);
  const json = JSON.parse(fs.readFileSync(path.join(outDir, "agent-creator-data.json"), "utf8"));
  assert.ok(json.skills.length >= 50);
  const js = fs.readFileSync(path.join(outDir, "agent-creator-data.js"), "utf8");
  assert.ok(js.startsWith("// Generated by scripts/build-agent-creator-data.js"));
  assert.ok(js.includes("window.AGENT_CREATOR_DATA = {"));
});

test("committed agent-creator-data.json is valid and well-formed", () => {
  const committed = JSON.parse(
    fs.readFileSync(path.join(__dirname, "..", "agent-creator-data.json"), "utf8")
  );
  assert.equal(committed.schema_version, "1.0");
  assert.ok(Array.isArray(committed.skills) && committed.skills.length > 0);
  assert.ok(Array.isArray(committed.personas) && committed.personas.length > 0);
});
