const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const {
  buildRegistry,
  validateEntry,
  liveUrl,
  PAGES_BASE_URL,
} = require("../scripts/build-hub-registry.js");

function writeEntries(dir, entries) {
  for (const [name, body] of Object.entries(entries)) {
    fs.writeFileSync(
      path.join(dir, name),
      typeof body === "string" ? body : JSON.stringify(body),
    );
  }
}

test("buildRegistry assembles hub entries from data/hub/entries JSON files", () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "hub-entries-"));
  writeEntries(dir, {
    "my-page.json": {
      slug: "my-page",
      title: "My Page",
      description: "A test page.",
      path: "./my-page/",
      tag: "Product",
      issue: 15510,
    },
    "other.json": {
      slug: "other",
      title: "Other",
      description: "Another page.",
      path: "./other.html",
    },
    "notes.txt": "ignored — not a .json entry",
  });

  const registry = buildRegistry(dir);
  assert.equal(registry.schema_version, "1.0");
  assert.equal(registry.repo, "midnghtsapphire/revvel-standards");
  assert.equal(registry.pages_base_url, PAGES_BASE_URL);
  assert.equal(registry.entries.length, 2);

  const myPage = registry.entries.find((e) => e.slug === "my-page");
  assert.equal(myPage.issue, 15510);
  assert.equal(myPage.tag, "Product");
  assert.equal(myPage.live_url, PAGES_BASE_URL + "my-page/");

  const other = registry.entries.find((e) => e.slug === "other");
  assert.equal(other.tag, "Website", "tag should default to Website");
  assert.equal(other.issue, null);
  assert.equal(other.live_url, PAGES_BASE_URL + "other.html");
});

test("buildRegistry rejects malformed entries", () => {
  const cases = [
    [
      "bad-slug.json",
      { slug: "Bad Slug", title: "t", description: "d", path: "./x/" },
      /invalid slug/,
    ],
    [
      "no-title.json",
      { slug: "no-title", description: "d", path: "./x/" },
      /missing title/,
    ],
    [
      "no-desc.json",
      { slug: "no-desc", title: "t", path: "./x/" },
      /missing description/,
    ],
    [
      "ext-url.json",
      {
        slug: "ext-url",
        title: "t",
        description: "d",
        path: "https://evil.example/",
      },
      /invalid path/,
    ],
    [
      "traversal.json",
      { slug: "traversal", title: "t", description: "d", path: "./../secrets" },
      /invalid path/,
    ],
    [
      "bad-issue.json",
      {
        slug: "bad-issue",
        title: "t",
        description: "d",
        path: "./x/",
        issue: "15510",
      },
      /invalid issue/,
    ],
    ["not-json.json", "{ nope", /invalid JSON/],
  ];
  for (const [name, body, re] of cases) {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "hub-bad-"));
    writeEntries(dir, { [name]: body });
    assert.throws(() => buildRegistry(dir), re, `${name} should be rejected`);
  }
});

test("buildRegistry rejects duplicate slugs", () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "hub-dup-"));
  const entry = { slug: "dup", title: "t", description: "d", path: "./dup/" };
  writeEntries(dir, { "a.json": entry, "b.json": entry });
  assert.throws(() => buildRegistry(dir), /duplicate slug/);
});

test("validateEntry and liveUrl work standalone", () => {
  assert.doesNotThrow(() =>
    validateEntry(
      { slug: "ok", title: "t", description: "d", path: "./ok/" },
      "ok.json",
    ),
  );
  assert.equal(liveUrl("./my-page/"), PAGES_BASE_URL + "my-page/");
});

test("CLI writes both JSON and window-global artifacts", () => {
  const entriesDir = fs.mkdtempSync(path.join(os.tmpdir(), "hub-cli-entries-"));
  const outDir = fs.mkdtempSync(path.join(os.tmpdir(), "hub-cli-out-"));
  writeEntries(entriesDir, {
    "cli-page.json": {
      slug: "cli-page",
      title: "CLI Page",
      description: "d",
      path: "./cli-page/",
    },
  });
  const { execFileSync } = require("node:child_process");
  execFileSync(process.execPath, [
    path.join(__dirname, "..", "scripts", "build-hub-registry.js"),
    "--entries-dir",
    entriesDir,
    "--out-dir",
    outDir,
  ]);
  const json = JSON.parse(
    fs.readFileSync(path.join(outDir, "hub-registry.json"), "utf8"),
  );
  assert.equal(json.entries.length, 1);
  const js = fs.readFileSync(path.join(outDir, "hub-registry.js"), "utf8");
  assert.ok(js.startsWith("// Generated by scripts/build-hub-registry.js"));
  assert.ok(js.includes("window.HUB_REGISTRY = {"));
});

test("committed hub-registry outputs match the committed entries", () => {
  const root = path.join(__dirname, "..");
  const committed = JSON.parse(
    fs.readFileSync(path.join(root, "hub-registry.json"), "utf8"),
  );
  const rebuilt = buildRegistry();
  assert.deepEqual(
    committed,
    rebuilt,
    "hub-registry.json is stale — run `node scripts/build-hub-registry.js` and commit",
  );
  const js = fs.readFileSync(path.join(root, "hub-registry.js"), "utf8");
  assert.ok(
    js.includes("window.HUB_REGISTRY = "),
    "hub-registry.js missing window global",
  );
});

test("index.html wires the generated hub registry into the Live tabs grid", () => {
  const html = fs.readFileSync(
    path.join(__dirname, "..", "index.html"),
    "utf8",
  );
  assert.ok(
    html.includes('id="hub-grid"'),
    "hub grid must be addressable for generated cards",
  );
  assert.ok(
    html.includes('src="hub-registry.js"'),
    "index.html must load hub-registry.js",
  );
  assert.ok(
    html.includes("window.HUB_REGISTRY"),
    "index.html must render from window.HUB_REGISTRY",
  );
});
