"use strict";

const test = require("node:test");
const assert = require("node:assert");
const fs = require("fs");
const path = require("path");

const smap = require("../scripts/secrets-map");

const SAMPLE = `
name: Sample
env:
  GH_TOKEN: \${{ secrets.ADMIN_GITHUB_TOKEN != '' && secrets.ADMIN_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
jobs:
  a:
    steps:
      - env:
          DOPPLER_TOKEN: \${{ secrets.DOPPLER_AGENT_TOKEN || secrets.DOPPLER_TOKEN || secrets.DOPPLER_API_KEY }}
          OPENROUTER_API_KEY: \${{ secrets.OPENROUTER_API_KEY }}
`;

test("extractSecrets finds every distinct secrets.NAME reference", () => {
  const names = smap.extractSecrets(SAMPLE);
  assert.ok(names.has("ADMIN_GITHUB_TOKEN"));
  assert.ok(names.has("GITHUB_TOKEN"));
  assert.ok(names.has("DOPPLER_AGENT_TOKEN"));
  assert.ok(names.has("OPENROUTER_API_KEY"));
  assert.equal(names.size, 6);
});

test("extractFallbackChains captures || chains including the != '' && pattern", () => {
  const chains = smap.extractFallbackChains(SAMPLE);
  assert.ok(chains.includes("ADMIN_GITHUB_TOKEN → GITHUB_TOKEN"));
  assert.ok(
    chains.includes("DOPPLER_AGENT_TOKEN → DOPPLER_TOKEN → DOPPLER_API_KEY"),
  );
  // single-secret expressions are not chains
  assert.ok(!chains.some((c) => c === "OPENROUTER_API_KEY"));
});

test("extractLedgerNames reads the presence-ledger NAMES list", () => {
  const text = fs.readFileSync(
    path.join(__dirname, "../.github/workflows/secrets-backup-daily.yml"),
    "utf8",
  );
  const names = smap.extractLedgerNames(text);
  assert.ok(names.includes("OPENROUTER_API_KEY"));
  assert.ok(names.length >= 5);
});

test("scanWorkflows over the real workflows finds the core secrets", () => {
  const map = smap.scanWorkflows();
  assert.ok(map.has("OPENROUTER_API_KEY"));
  assert.ok(map.has("ADMIN_GITHUB_TOKEN"));
  assert.ok(map.get("OPENROUTER_API_KEY").workflows.length > 0);
});

test("renderMarkdown never contains values — only names, and marks Doppler decommissioned", () => {
  const map = smap.scanWorkflows();
  const md = smap.renderMarkdown(map, ["OPENROUTER_API_KEY"]);
  assert.ok(md.startsWith("<!-- generated by scripts/secrets-map.js"));
  assert.ok(md.includes("never values"));
  assert.ok(md.includes("`OPENROUTER_API_KEY`"));
  if (map.has("DOPPLER_TOKEN")) {
    assert.ok(md.includes("decommissioned"));
  }
});

test("committed docs/SECRETS_MAP.md is fresh (regenerate with npm run secrets:map)", () => {
  const map = smap.scanWorkflows();
  const ledger = smap.extractLedgerNames(
    fs.readFileSync(
      path.join(__dirname, "../.github/workflows/secrets-backup-daily.yml"),
      "utf8",
    ),
  );
  const next = smap.renderMarkdown(map, ledger);
  const current = fs.readFileSync(
    path.join(__dirname, "../docs/SECRETS_MAP.md"),
    "utf8",
  );
  assert.equal(smap.normalize(current), smap.normalize(next));
});
