const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const PACKAGES_DIR = path.join(__dirname, "..", "packages");

const {
  flattenTokens,
  loadTokens,
  toScss,
  toCss,
  build,
} = require("../packages/style-dictionary/build.js");
const {
  scssToTokens,
  tokensToScss,
} = require("../packages/style-dictionary/scss-to-tokens.js");

const EXPECTED_PACKAGES = [
  "browserslist-config",
  "eslint-config",
  "prettier-config",
  "style-dictionary",
  "stylelint-config",
  "typescript-config",
];

test("every shared package has a valid scoped manifest and README", () => {
  for (const name of EXPECTED_PACKAGES) {
    const dir = path.join(PACKAGES_DIR, name);
    assert.ok(fs.existsSync(dir), `packages/${name} exists`);
    const manifest = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
    assert.strictEqual(manifest.name, `@revvel/${name}`, `packages/${name} is @revvel-scoped`);
    assert.match(manifest.version, /^\d+\.\d+\.\d+$/, `packages/${name} has a semver version`);
    assert.ok(manifest.license, `packages/${name} declares a license`);
    assert.ok(
      fs.existsSync(path.join(dir, "README.md")),
      `packages/${name} ships integration docs (README.md)`,
    );
    for (const target of Object.values(manifest.exports || {})) {
      // dist/ outputs are generated by the build; assert only source exports here.
      if (typeof target === "string" && !target.startsWith("./dist/")) {
        assert.ok(
          fs.existsSync(path.join(dir, target)),
          `packages/${name} export target ${target} exists`,
        );
      }
    }
  }
});

test("prettier config is valid JSON with deterministic formatting keys", () => {
  const config = require("../packages/prettier-config/index.json");
  assert.strictEqual(config.tabWidth, 2);
  assert.strictEqual(config.semi, true);
  assert.strictEqual(config.endOfLine, "lf");
});

test("browserslist config exports a non-empty array of query strings", () => {
  const queries = require("../packages/browserslist-config/index.js");
  assert.ok(Array.isArray(queries) && queries.length > 0);
  for (const q of queries) assert.strictEqual(typeof q, "string");
});

test("stylelint config blocks new local SCSS dollar variables", () => {
  const config = require("../packages/stylelint-config/index.js");
  assert.deepStrictEqual(config.extends, ["stylelint-config-standard-scss"]);
  const rule = config.rules["scss/dollar-variable-pattern"];
  assert.ok(Array.isArray(rule), "dollar-variable-pattern rule is configured");
  assert.doesNotMatch("any-new-variable", new RegExp(rule[0]), "pattern rejects new variables");
  assert.match(rule[1].message, /style-dictionary/i, "message points at the token pipeline");
});

test("eslint config module exposes buildConfig and build-output ignores", () => {
  const { buildConfig, IGNORE_PATTERNS } = require("../packages/eslint-config/index.js");
  assert.strictEqual(typeof buildConfig, "function");
  assert.ok(IGNORE_PATTERNS.includes(".next/**"));
  assert.ok(IGNORE_PATTERNS.includes("node_modules/**"));
});

test("typescript configs parse and next.json extends base.json", () => {
  const base = JSON.parse(
    fs.readFileSync(path.join(PACKAGES_DIR, "typescript-config", "base.json"), "utf8"),
  );
  const next = JSON.parse(
    fs.readFileSync(path.join(PACKAGES_DIR, "typescript-config", "next.json"), "utf8"),
  );
  assert.strictEqual(base.compilerOptions.strict, true);
  assert.strictEqual(next.extends, "./base.json");
  assert.strictEqual(next.compilerOptions.jsx, "react-jsx");
});

test("flattenTokens flattens nested categories into dashed names", () => {
  const flat = flattenTokens({
    color: { "bg-primary": { value: "#090d16", type: "color" } },
    spacing: { sm: { value: "8px" } },
  });
  assert.deepStrictEqual(Object.keys(flat), ["color-bg-primary", "spacing-sm"]);
  assert.strictEqual(flat["color-bg-primary"].value, "#090d16");
});

test("flattenTokens rejects malformed token leaves", () => {
  assert.throws(() => flattenTokens({ color: { bad: "not-an-object" } }), /Invalid token/);
});

test("token build emits SCSS variables and CSS custom properties for every token", () => {
  const distDir = fs.mkdtempSync(path.join(os.tmpdir(), "sd-dist-"));
  const flat = build({ distDir });
  const scss = fs.readFileSync(path.join(distDir, "_variables.scss"), "utf8");
  const css = fs.readFileSync(path.join(distDir, "variables.css"), "utf8");
  const flatJson = JSON.parse(fs.readFileSync(path.join(distDir, "tokens.flat.json"), "utf8"));
  assert.ok(Object.keys(flat).length > 0);
  for (const [name, def] of Object.entries(flat)) {
    assert.ok(scss.includes(`$${name}: ${def.value};`), `SCSS contains ${name}`);
    assert.ok(css.includes(`--${name}: ${def.value};`), `CSS contains ${name}`);
  }
  assert.deepStrictEqual(flatJson, flat);
});

test("committed dist output matches a fresh build (no drift)", () => {
  const distDir = path.join(PACKAGES_DIR, "style-dictionary", "dist");
  const flat = flattenTokens(loadTokens());
  assert.strictEqual(fs.readFileSync(path.join(distDir, "_variables.scss"), "utf8"), toScss(flat));
  assert.strictEqual(fs.readFileSync(path.join(distDir, "variables.css"), "utf8"), toCss(flat));
  assert.strictEqual(
    fs.readFileSync(path.join(distDir, "tokens.flat.json"), "utf8"),
    `${JSON.stringify(flat, null, 2)}\n`,
  );
});

test("scssToTokens converts simple declarations and reports unsafe ones", () => {
  const { tokens, skipped } = scssToTokens(
    [
      "$brand-pink: #ec4899;",
      "$gap: 8px !default;",
      "// $commented: out;",
      "$map: (a: 1, b: 2);",
      "$interp: #{$brand-pink};",
    ].join("\n"),
  );
  assert.deepStrictEqual(tokens, {
    "brand-pink": { value: "#ec4899" },
    gap: { value: "8px" },
  });
  assert.strictEqual(skipped.length, 2, "maps and interpolation are skipped, not mangled");
});

test("SCSS -> JSON -> SCSS round trip reproduces the original declarations", () => {
  const original = "$brand-pink: #ec4899;\n$spacing-md: 16px;\n$font-stack: system-ui, sans-serif;\n";
  const { tokens, skipped } = scssToTokens(original);
  assert.strictEqual(skipped.length, 0);
  assert.strictEqual(tokensToScss(tokens), original, "round trip is lossless");
});
