#!/usr/bin/env node
/**
 * @revvel/style-dictionary — token build.
 *
 * Reads every JSON token file under tokens/ (Style Dictionary "value" format:
 * nested categories where each leaf is `{ "value": ..., "type": ... }`) and
 * emits:
 *
 *   dist/_variables.scss  — `$category-name: value;` SCSS variables
 *   dist/variables.css    — `--category-name: value;` custom properties on :root
 *   dist/tokens.flat.json — flat `{ "$category-name": { "value": ... } }` map
 *
 * Why no style-dictionary npm dependency: the token format is Style
 * Dictionary-compatible, but this repo keeps root tooling lightweight and the
 * transform we need (nested JSON -> SCSS/CSS variables) is ~50 lines. If a
 * product later needs platform outputs (iOS, Android), point the real
 * style-dictionary CLI at tokens/ — no token changes required.
 *
 * Fallback / what to check if it fails: a non-object leaf or a leaf missing
 * `value` aborts the build with the offending token path so bad tokens never
 * ship silently.
 */
"use strict";

const fs = require("node:fs");
const path = require("node:path");

const TOKENS_DIR = path.join(__dirname, "tokens");
const DIST_DIR = path.join(__dirname, "dist");

/**
 * Flatten a nested token tree into `name -> definition` pairs.
 * `{ color: { "bg-primary": { value: "#090d16" } } }` becomes
 * `{ "color-bg-primary": { value: "#090d16" } }`.
 */
function flattenTokens(tree, prefix = []) {
  const flat = {};
  for (const [key, node] of Object.entries(tree)) {
    if (node === null || typeof node !== "object") {
      throw new Error(
        `Invalid token at "${[...prefix, key].join(".")}": expected an object, got ${JSON.stringify(node)}`,
      );
    }
    if (Object.prototype.hasOwnProperty.call(node, "value")) {
      const name = [...prefix, key].join("-");
      if (Object.prototype.hasOwnProperty.call(flat, name)) {
        throw new Error(`Duplicate flattened token "${name}"`);
      }
      flat[name] = node;
    } else {
      const nested = flattenTokens(node, [...prefix, key]);
      for (const [name, definition] of Object.entries(nested)) {
        if (Object.prototype.hasOwnProperty.call(flat, name)) {
          throw new Error(`Duplicate flattened token "${name}"`);
        }
        flat[name] = definition;
      }
    }
  }
  return flat;
}

/** Load and merge every *.json file in the tokens directory. */
function loadTokens(dir = TOKENS_DIR) {
  const merged = {};
  const files = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .sort();
  if (files.length === 0) {
    throw new Error(`No token files found in ${dir}`);
  }
  for (const file of files) {
    const parsed = JSON.parse(fs.readFileSync(path.join(dir, file), "utf8"));
    for (const [category, body] of Object.entries(parsed)) {
      const existing = merged[category] || {};
      for (const key of Object.keys(body)) {
        // Never silently drop a token: a duplicate key across files would
        // overwrite the earlier definition, so fail loudly instead.
        if (Object.prototype.hasOwnProperty.call(existing, key)) {
          throw new Error(
            `Duplicate token "${category}.${key}" in ${file} — already defined in an earlier token file`,
          );
        }
      }
      merged[category] = { ...existing, ...body };
    }
  }
  return merged;
}

const GENERATED_HEADER =
  "Generated by @revvel/style-dictionary build.js — do not edit by hand.\n" +
  " * Add or change tokens in tokens/*.json, then run `npm run build`.";

function toScss(flat) {
  const lines = [`/* ${GENERATED_HEADER} */`];
  for (const [name, def] of Object.entries(flat)) {
    lines.push(`$${name}: ${def.value};`);
  }
  return `${lines.join("\n")}\n`;
}

function toCss(flat) {
  const lines = [`/* ${GENERATED_HEADER} */`, ":root {"];
  for (const [name, def] of Object.entries(flat)) {
    lines.push(`  --${name}: ${def.value};`);
  }
  lines.push("}");
  return `${lines.join("\n")}\n`;
}

function build({ tokensDir = TOKENS_DIR, distDir = DIST_DIR } = {}) {
  const tokens = loadTokens(tokensDir);
  const flat = flattenTokens(tokens);
  for (const [name, def] of Object.entries(flat)) {
    if (def.value === undefined || def.value === null || def.value === "") {
      throw new Error(`Token "${name}" has an empty value`);
    }
  }
  fs.mkdirSync(distDir, { recursive: true });
  fs.writeFileSync(path.join(distDir, "_variables.scss"), toScss(flat));
  fs.writeFileSync(path.join(distDir, "variables.css"), toCss(flat));
  fs.writeFileSync(
    path.join(distDir, "tokens.flat.json"),
    `${JSON.stringify(flat, null, 2)}\n`,
  );
  return flat;
}

module.exports = { flattenTokens, loadTokens, toScss, toCss, build, TOKENS_DIR, DIST_DIR };

if (require.main === module) {
  const flat = build();
  console.log(
    `Built ${Object.keys(flat).length} tokens -> dist/_variables.scss, dist/variables.css, dist/tokens.flat.json`,
  );
}
