/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js during local development and kept here so
// strict TypeScript checks have the expected framework declarations in CI.
