import { ReviewFinding, ReviewResult, SEVERITY_ORDER, Severity } from "./types";

export function sortFindings(findings: ReviewFinding[]): ReviewFinding[] {
  return [...findings].sort((a, b) => {
    const sev = SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity];
    if (sev !== 0) return sev;
    return (a.file || "").localeCompare(b.file || "") || a.title.localeCompare(b.title);
  });
}

export function countBySeverity(findings: ReviewFinding[]): Record<Severity, number> {
  const base: Record<Severity, number> = {
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
    info: 0,
  };
  for (const f of findings) {
    base[f.severity] += 1;
  }
  return base;
}

export function buildMarkdownReport(result: Omit<ReviewResult, "markdown">): string {
  const sorted = sortFindings(result.findings);
  const lines: string[] = [
    "# Groq Code Review Report",
    "",
    `**Provider:** ${result.stats.provider} · **Model:** ${result.stats.model}`,
    `**Chunks:** ${result.stats.chunkCount} · **Findings:** ${result.stats.findingCount}`,
    "",
    "## Executive summary",
    "",
    result.summary,
    "",
    "## Severity totals",
    "",
    `| Severity | Count |`,
    `| --- | ---: |`,
    `| critical | ${result.stats.critical} |`,
    `| high | ${result.stats.high} |`,
    `| medium | ${result.stats.medium} |`,
    `| low | ${result.stats.low} |`,
    `| info | ${result.stats.info} |`,
    "",
    "## Findings",
    "",
  ];

  if (!sorted.length) {
    lines.push("_No findings. Diff looks clean under the active reviewer._", "");
  } else {
    for (const f of sorted) {
      const loc = [f.file, f.lineHint ? `L${f.lineHint}` : undefined].filter(Boolean).join(" ");
      lines.push(`### [${f.severity}] ${f.title}`);
      lines.push("");
      if (loc) lines.push(`- **Location:** \`${loc}\``);
      lines.push(`- **Rule:** \`${f.ruleId}\``);
      lines.push(`- **Chunk:** ${f.chunkIndex + 1}`);
      lines.push(`- **Detail:** ${f.detail}`);
      lines.push("");
    }
  }

  lines.push("## Per-chunk notes", "");
  for (const chunk of result.chunkReviews) {
    lines.push(`### Chunk ${chunk.chunkIndex + 1}: ${chunk.label}`);
    lines.push("");
    lines.push(`${chunk.summary} _(provider: ${chunk.provider})_`);
    lines.push("");
  }

  lines.push("---");
  lines.push("_Generated by products/groq-code-review — Groq when keyed, local heuristics otherwise._");
  lines.push("");
  return lines.join("\n");
}

export function buildGithubReviewBody(result: ReviewResult): string {
  const top = sortFindings(result.findings).slice(0, 20);
  const bullets = top.length
    ? top
        .map((f) => {
          const loc = f.file ? ` (\`${f.file}${f.lineHint ? `:${f.lineHint}` : ""}\`)` : "";
          return `- **[${f.severity}]** ${f.title}${loc} — ${f.detail}`;
        })
        .join("\n")
    : "- No material findings from automated review.";

  return [
    "### 🤖 Groq Code Review",
    "",
    result.summary,
    "",
    `Chunks reviewed: **${result.stats.chunkCount}** · Provider: **${result.stats.provider}** · Model: **${result.stats.model}**`,
    "",
    "#### Top findings",
    bullets,
    "",
    "<details><summary>Full markdown report</summary>",
    "",
    result.markdown,
    "",
    "</details>",
    "",
    "_Posted by groq-code-review. Add `[skip-review]` to the PR title to bypass in workflows that honor it._",
  ].join("\n");
}
