#!/usr/bin/env python3
"""
blue_ocean_generator.py — Auto-builds CLIs, PDF reports, and FastAPI servers
penny-sovereign-yield-scout | Freedom Angel Corp / Audrey Evans

Scaffolds new yield-scout tools on demand using Jinja2 templates.

Usage:
    # Scaffold a new CLI tool
    python tools/blue_ocean_generator.py --type cli --name my-yield-cli --protocol morpho

    # Scaffold a new FastAPI server
    python tools/blue_ocean_generator.py --type api --name morpho-compounder --port 8766

    # Generate a PDF yield report from scan results
    python tools/blue_ocean_generator.py --type pdf --title "Weekly Yield Report" --data results.json
"""

from __future__ import annotations

import argparse
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from rich.console import Console

console = Console()

# ─── Output directory ─────────────────────────────────────────────────────────
GENERATED_DIR = Path("generated")


# ─── Jinja2-style template renderer (no external dep required) ───────────────

def render(template: str, context: dict[str, Any]) -> str:
    """Simple string-format-based template renderer."""
    for key, value in context.items():
        template = template.replace("{{" + key + "}}", str(value))
    return template


# ─── CLI scaffold template ────────────────────────────────────────────────────

CLI_MAIN_TEMPLATE = '''\
#!/usr/bin/env python3
"""
{{name}} — Yield Scout CLI for {{protocol}}
Auto-generated by blue_ocean_generator.py
Freedom Angel Corp / Audrey Evans
"""
from __future__ import annotations
import argparse
import json
import os
from pathlib import Path

import httpx
from dotenv import load_dotenv
from rich.console import Console
from rich.table import Table

load_dotenv()
console = Console()

DEFILLAMA_BASE = os.getenv("DEFILLAMA_BASE_URL", "https://yields.llama.fi")


def fetch_pools(protocol: str) -> list[dict]:
    """Fetch yield pools for a specific protocol from DeFiLlama."""
    resp = httpx.get(f"{DEFILLAMA_BASE}/pools", timeout=30)
    resp.raise_for_status()
    data = resp.json().get("data", [])
    return [p for p in data if protocol.lower() in p.get("project", "").lower()]


def display_pools(pools: list[dict], top: int = 10) -> None:
    table = Table(title=f"{{name}} — Top Pools", show_lines=True)
    table.add_column("#", style="dim", width=3)
    table.add_column("Pool", style="bold cyan")
    table.add_column("Chain", style="white")
    table.add_column("APY", style="bold yellow")
    table.add_column("TVL (USD)", style="white")

    pools_sorted = sorted(pools, key=lambda p: p.get("apy", 0) or 0, reverse=True)
    for i, pool in enumerate(pools_sorted[:top], 1):
        table.add_row(
            str(i),
            pool.get("symbol", "—"),
            pool.get("chain", "—"),
            f"{pool.get('apy', 0):.2f}%" if pool.get("apy") else "—",
            f"${pool.get('tvlUsd', 0):,.0f}",
        )
    console.print(table)


def main() -> None:
    parser = argparse.ArgumentParser(description="{{name}} — {{protocol}} yield CLI")
    parser.add_argument("--top", type=int, default=10)
    parser.add_argument("--output", type=str)
    args = parser.parse_args()

    console.rule("[bold cyan]{{name}}[/]")
    pools = fetch_pools("{{protocol}}")
    display_pools(pools, top=args.top)

    if args.output:
        with open(args.output, "w") as f:
            json.dump(pools[: args.top], f, indent=2)
        console.print(f"Saved to [cyan]{args.output}[/]")


if __name__ == "__main__":
    main()
'''

CLI_REQUIREMENTS_TEMPLATE = '''\
httpx>=0.27.0
python-dotenv>=1.0.0
rich>=13.0.0
'''

CLI_README_TEMPLATE = '''\
# {{name}}

Auto-generated CLI for **{{protocol}}** yield data.
Generated by `blue_ocean_generator.py` on {{date}}.

## Usage

```bash
pip install -r requirements.txt
python main.py --top 10
python main.py --top 20 --output results.json
```

## License

All Rights Reserved. Copyright 2026 Freedom Angel Corp / Audrey Evans.
'''

# ─── FastAPI scaffold template ────────────────────────────────────────────────

API_MAIN_TEMPLATE = '''\
#!/usr/bin/env python3
"""
{{name}} — FastAPI yield server
Auto-generated by blue_ocean_generator.py
Freedom Angel Corp / Audrey Evans
"""
from __future__ import annotations
import os
from datetime import datetime, timezone

import httpx
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

load_dotenv()

app = FastAPI(
    title="{{name}}",
    description="Auto-generated FastAPI yield server",
    version="1.0.0",
)

DEFILLAMA_BASE = os.getenv("DEFILLAMA_BASE_URL", "https://yields.llama.fi")


class CompoundRequest(BaseModel):
    protocol: str
    pool_id: str
    wallet: str


@app.get("/health")
def health() -> dict:
    return {"status": "ok", "timestamp": datetime.now(timezone.utc).isoformat()}


@app.get("/pools")
def get_pools(protocol: str = "") -> dict:
    """Fetch live pool data from DeFiLlama."""
    try:
        resp = httpx.get(f"{DEFILLAMA_BASE}/pools", timeout=30)
        resp.raise_for_status()
        data = resp.json().get("data", [])
        if protocol:
            data = [p for p in data if protocol.lower() in p.get("project", "").lower()]
        return {"count": len(data), "pools": data[:50]}
    except Exception as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc


@app.post("/compound")
def compound(req: CompoundRequest) -> dict:
    """Trigger a compound action (stub — wire to web3 in production)."""
    return {
        "status": "queued",
        "protocol": req.protocol,
        "pool_id": req.pool_id,
        "wallet": req.wallet,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "note": "Connect web3 signer to execute on-chain.",
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port={{port}})
'''

API_DOCKERFILE_TEMPLATE = '''\
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE {{port}}
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "{{port}}"]
'''

API_ENV_TEMPLATE = '''\
DEFILLAMA_BASE_URL=https://yields.llama.fi
COMPOUND_WALLET_ADDRESS=0xYourWalletAddressHere
COMPOUND_PRIVATE_KEY=NEVER_COMMIT_YOUR_REAL_PRIVATE_KEY
'''

API_REQUIREMENTS_TEMPLATE = '''\
fastapi>=0.110.0
uvicorn[standard]>=0.29.0
httpx>=0.27.0
python-dotenv>=1.0.0
pydantic>=2.0.0
'''


# ─── PDF report generator ─────────────────────────────────────────────────────

def generate_pdf_report(title: str, data_path: str | None, output_dir: Path) -> Path:
    """Generate a glassmorphic-style PDF yield report."""
    try:
        from fpdf import FPDF  # type: ignore

        data: list[dict] = []
        if data_path:
            with open(data_path, encoding="utf-8") as f:
                data = json.load(f)

        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        # Header
        pdf.set_fill_color(10, 10, 26)
        pdf.set_text_color(200, 169, 90)
        pdf.set_font("Helvetica", "B", 20)
        pdf.cell(0, 15, title, ln=True, align="C")

        pdf.set_text_color(200, 200, 200)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(
            0, 8,
            f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} | Freedom Angel Corp",
            ln=True, align="C",
        )
        pdf.ln(10)

        # Table header
        pdf.set_fill_color(30, 30, 60)
        pdf.set_text_color(255, 215, 0)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(10, 8, "#", border=1, fill=True)
        pdf.cell(50, 8, "Protocol", border=1, fill=True)
        pdf.cell(40, 8, "Pool", border=1, fill=True)
        pdf.cell(25, 8, "APY", border=1, fill=True)
        pdf.cell(35, 8, "TVL (USD)", border=1, fill=True)
        pdf.cell(30, 8, "Score", border=1, fill=True, ln=True)

        pdf.set_text_color(220, 220, 220)
        pdf.set_font("Helvetica", "", 8)
        for i, row in enumerate(data[:25], 1):
            fill = (i % 2 == 0)
            if fill:
                pdf.set_fill_color(20, 20, 40)
            else:
                pdf.set_fill_color(15, 15, 30)
            pdf.cell(10, 7, str(i), border=1, fill=True)
            pdf.cell(50, 7, str(row.get("project", "—"))[:25], border=1, fill=True)
            pdf.cell(40, 7, str(row.get("symbol", "—"))[:20], border=1, fill=True)
            apy = row.get("apy")
            pdf.cell(25, 7, f"{apy:.2f}%" if apy else "—", border=1, fill=True)
            tvl = row.get("tvlUsd", 0) or 0
            pdf.cell(35, 7, f"${tvl:,.0f}", border=1, fill=True)
            score = row.get("opportunity_score")
            pdf.cell(30, 7, f"{score:.4f}" if score else "—", border=1, fill=True, ln=True)

        pdf.ln(10)
        pdf.set_text_color(150, 150, 150)
        pdf.set_font("Helvetica", "I", 7)
        pdf.cell(0, 5, "All Rights Reserved. Copyright 2026 Freedom Angel Corp / Audrey Evans.", ln=True, align="C")

        output_path = output_dir / f"{title.lower().replace(' ', '-')}-{datetime.now(timezone.utc).strftime('%Y-%m-%d')}.pdf"
        pdf.output(str(output_path))
        return output_path

    except ImportError:
        console.print("[yellow]fpdf2 not installed. Run: pip install fpdf2[/]")
        # Fallback: write markdown
        output_path = output_dir / f"{title.lower().replace(' ', '-')}.md"
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(f"# {title}\n\nGenerated: {datetime.now(timezone.utc).isoformat()}\n\n")
            if data_path:
                f.write(f"Data source: {data_path}\n\n")
                with open(data_path, encoding="utf-8") as df:
                    raw = json.load(df)
                f.write("```json\n" + json.dumps(raw[:10], indent=2) + "\n```\n")
        console.print(f"[yellow]PDF generation requires fpdf2. Saved as Markdown: {output_path}[/]")
        return output_path


# ─── Main generator ───────────────────────────────────────────────────────────

def scaffold_cli(name: str, protocol: str) -> None:
    dest = GENERATED_DIR / name
    dest.mkdir(parents=True, exist_ok=True)
    ctx = {"name": name, "protocol": protocol, "date": datetime.now(timezone.utc).date().isoformat()}

    (dest / "main.py").write_text(render(CLI_MAIN_TEMPLATE, ctx), encoding="utf-8")
    (dest / "requirements.txt").write_text(render(CLI_REQUIREMENTS_TEMPLATE, ctx), encoding="utf-8")
    (dest / "README.md").write_text(render(CLI_README_TEMPLATE, ctx), encoding="utf-8")

    console.print(f"✅ CLI scaffold created at [cyan]{dest}[/]")
    console.print("   Files: main.py, requirements.txt, README.md")


def scaffold_api(name: str, port: int) -> None:
    dest = GENERATED_DIR / name
    dest.mkdir(parents=True, exist_ok=True)
    ctx = {"name": name, "port": str(port)}

    (dest / "main.py").write_text(render(API_MAIN_TEMPLATE, ctx), encoding="utf-8")
    (dest / "Dockerfile").write_text(render(API_DOCKERFILE_TEMPLATE, ctx), encoding="utf-8")
    (dest / ".env.example").write_text(render(API_ENV_TEMPLATE, ctx), encoding="utf-8")
    (dest / "requirements.txt").write_text(render(API_REQUIREMENTS_TEMPLATE, ctx), encoding="utf-8")

    console.print(f"✅ API scaffold created at [cyan]{dest}[/]")
    console.print(f"   Files: main.py, Dockerfile, .env.example, requirements.txt")
    console.print(f"   Start: uvicorn {name}.main:app --reload --port {port}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Blue Ocean Generator — scaffold CLIs, APIs, and PDF reports"
    )
    parser.add_argument("--type", choices=["cli", "api", "pdf"], required=True)
    parser.add_argument("--name", type=str, help="Name for CLI or API scaffold")
    parser.add_argument("--protocol", type=str, default="defi", help="Protocol name (for CLI type)")
    parser.add_argument("--port", type=int, default=8766, help="Port number (for API type)")
    parser.add_argument("--title", type=str, default="Yield Report", help="Report title (for PDF type)")
    parser.add_argument("--data", type=str, help="Path to JSON data file (for PDF type)")

    args = parser.parse_args()
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    reports_dir = GENERATED_DIR / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)

    console.rule("[bold cyan]🌊 Blue Ocean Generator[/]")

    if args.type == "cli":
        if not args.name:
            parser.error("--name is required for --type cli")
        scaffold_cli(args.name, args.protocol)

    elif args.type == "api":
        if not args.name:
            parser.error("--name is required for --type api")
        scaffold_api(args.name, args.port)

    elif args.type == "pdf":
        output_path = generate_pdf_report(args.title, args.data, reports_dir)
        console.print(f"✅ PDF report generated: [cyan]{output_path}[/]")


if __name__ == "__main__":
    main()
