#!/usr/bin/env python3
"""
App Artifact Auditor — enforces Definition of Done across every app.

For each app in docs/app-deployments.yml it:
  1. Writes/refreshes docs/<app>/ARTIFACTS.md — the required-deliverable checklist
     with auto-detected status (the "required list for every app").
  2. Ensures the README carries a "## Live Deployment" section with the clickable
     live URL — but only when a real URL exists (no placeholders; DoD #2).
  3. Writes docs/APP_DELIVERY_STATUS.md — a one-glance dashboard of every app.

Principle: only code lives in the app dir; the deliverable record + test link
live in docs/. Idempotent — safe to run several times a day.

Requires: PyYAML
"""
import os
import re
import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "docs", "app-deployments.yml")
STATUS = os.path.join(ROOT, "docs", "APP_DELIVERY_STATUS.md")
REGISTRY = os.path.join(ROOT, "docs", "APP_REGISTRY.md")

URL_RE = re.compile(r"https?://[^\s)\"']+")
SECTION_RE = re.compile(r"\n## Live Deployment\b.*?(?=\n## |\Z)", re.S)


def read(path):
    try:
        with open(path, encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return ""


def grep_dir(app_dir, needle, exts=(".js", ".ts", ".tsx", ".jsx", ".py", ".json", ".md", ".env")):
    needle = needle.lower()
    for base, dirs, files in os.walk(app_dir):
        dirs[:] = [d for d in dirs if d not in ("node_modules", ".next", "dist", "build", ".git")]
        for fn in files:
            if fn.endswith(exts):
                if needle in read(os.path.join(base, fn)).lower():
                    return True
    return False


def detect(name, meta, registry_text):
    """Return dict of required-deliverable -> (ok: bool, note: str)."""
    path = meta.get("path", "")
    app_dir = os.path.join(ROOT, path) if path and path != "external" else None
    external = path == "external"
    live_url = (meta.get("live_url") or "").strip()
    readme = read(os.path.join(app_dir, "README.md")) if app_dir else ""

    has_web = bool(app_dir) and any(
        os.path.exists(os.path.join(app_dir, p))
        for p in ("index.html", "app", "pages", "src/app", "public/index.html")
    )

    checks = {}
    checks["Live Vercel URL"] = (bool(live_url), live_url or "no URL in app-deployments.yml")
    checks["README `## Live Deployment`"] = (
        bool(live_url) and "## Live Deployment" in readme and live_url in readme,
        "present" if (live_url and live_url in readme) else "section missing / URL not in README",
    )
    checks["Live web test interface"] = (
        has_web or external,
        "web app detected" if has_web else ("external repo" if external else "no web playground found (DoD: even API/CLI/MCP needs one)"),
    )
    checks[".mcp.json at root"] = (
        bool(app_dir) and os.path.exists(os.path.join(app_dir, ".mcp.json")),
        "present" if (app_dir and os.path.exists(os.path.join(app_dir, ".mcp.json"))) else "missing",
    )
    checks["Stripe monetization"] = (
        bool(app_dir) and grep_dir(app_dir, "stripe"),
        "stripe referenced" if (app_dir and grep_dir(app_dir, "stripe")) else "no stripe wiring found",
    )
    checks["Tests"] = (
        bool(app_dir) and (os.path.isdir(os.path.join(app_dir, "tests")) or grep_dir(app_dir, "describe(", (".test.js", ".test.ts", ".spec.ts"))),
        "tests present" if (app_dir and os.path.isdir(os.path.join(app_dir, "tests"))) else "no tests dir",
    )
    checks["Listed in APP_REGISTRY.md"] = (
        name.lower() in registry_text.lower(),
        "listed" if name.lower() in registry_text.lower() else "not registered",
    )
    return checks, live_url, external


def write_artifacts_md(name, meta, checks, live_url, external):
    out_dir = os.path.join(ROOT, "docs", name)
    os.makedirs(out_dir, exist_ok=True)
    done = sum(1 for ok, _ in checks.values() if ok)
    total = len(checks)
    lines = [
        f"# {name} — Delivery Artifacts",
        "",
        f"> Auto-generated by `scripts/app_artifact_auditor.py`. **{done}/{total} requirements met.**",
        f"> Code path: `{meta.get('path','?')}`" + (f"  ·  external repo: `{meta.get('repo')}`" if external else ""),
        f"> Live: " + (f"[{live_url}]({live_url})" if live_url else "**not deployed yet**"),
        "",
        "## Definition-of-Done requirements",
        "",
        "| Requirement | Status | Notes |",
        "| --- | :---: | --- |",
    ]
    for label, (ok, note) in checks.items():
        lines.append(f"| {label} | {'✅' if ok else '❌'} | {note} |")
    lines += [
        "",
        "## Required deliverable records",
        "",
        "These live here in `docs/` (only code goes in the app dir). Fill each as it ships:",
        "",
        "- [ ] **BOM** — bill of materials / components",
        "- [ ] **Research** — demand/chatter packet from the research engine",
        "- [ ] **Decision / ROI** — revenue ÷ cost gate (auto-approve ≥ 5)",
        "- [ ] **Deploy** — live URL + deploy record (above)",
        "- [ ] **Monetize** — Stripe products / pricing",
        "- [ ] **Market / SEO** — meta, OG, sitemap, listing copy",
        "- [ ] **Sales** — sales tracking / dashboard",
        "",
        "_See `standards/DELIVERY_MATRIX.md` and `docs/DEFINITION_OF_DONE.md`._",
        "",
    ]
    with open(os.path.join(out_dir, "ARTIFACTS.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def ensure_readme_link(meta, live_url):
    """Insert/refresh '## Live Deployment' in the README — only when a URL exists."""
    path = meta.get("path", "")
    if not live_url or path == "external" or not path:
        return False
    readme_path = os.path.join(ROOT, path, "README.md")
    text = read(readme_path)
    if not text:
        return False
    section = f"\n## Live Deployment\n\n▶️ **[Open the live app & test it]({live_url})**\n"
    if "## Live Deployment" in text:
        new = SECTION_RE.sub(section, text, count=1)
    else:
        # insert right after the first H1 title block
        m = re.search(r"^# .*$", text, re.M)
        idx = m.end() if m else 0
        new = text[:idx] + "\n" + section + text[idx:]
    if new != text:
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(new)
        return True
    return False


def main():
    manifest = yaml.safe_load(read(MANIFEST)) or {}
    apps = manifest.get("apps", {})
    registry_text = read(REGISTRY)

    rows = []
    for name, meta in apps.items():
        checks, live_url, external = detect(name, meta, registry_text)
        write_artifacts_md(name, meta, checks, live_url, external)
        ensure_readme_link(meta, live_url)
        done = sum(1 for ok, _ in checks.values() if ok)
        total = len(checks)
        gaps = [k for k, (ok, _) in checks.items() if not ok]
        rows.append((name, live_url, done, total, gaps))

    # dashboard
    rows.sort(key=lambda r: r[2] - r[3])  # most-incomplete first
    out = [
        "# App Delivery Status",
        "",
        "> Auto-generated by `scripts/app_artifact_auditor.py` (runs every 6h). "
        "Tracks Definition-of-Done compliance per app. Per-app detail: `docs/<app>/ARTIFACTS.md`.",
        "",
        f"**{len(rows)} apps.** "
        f"{sum(1 for r in rows if r[1])} have a live URL · "
        f"{sum(1 for r in rows if r[2] == r[3])} fully meet DoD.",
        "",
        "| App | Live URL | DoD | Top gaps |",
        "| --- | --- | :---: | --- |",
    ]
    for name, live_url, done, total, gaps in rows:
        link = f"[test]({live_url})" if live_url else "— none —"
        out.append(f"| [{name}](./{name}/ARTIFACTS.md) | {link} | {done}/{total} | {', '.join(gaps[:3]) or 'none 🎉'} |")
    out.append("")
    with open(STATUS, "w", encoding="utf-8") as f:
        f.write("\n".join(out))

    print(f"Audited {len(rows)} apps -> docs/<app>/ARTIFACTS.md + docs/APP_DELIVERY_STATUS.md")
    live = sum(1 for r in rows if r[1])
    print(f"Live URLs: {live}/{len(rows)}  (fill docs/app-deployments.yml to close gaps)")


if __name__ == "__main__":
    main()
