#!/usr/bin/env node
"use strict";

/**
 * SECRETS_MAP.md generator — names/locations ONLY, never values.
 *
 * Companion to scripts/connections-registry.js: the map is GENERATED from what
 * the workflows actually reference, so it cannot drift from reality. It answers
 * the owner's question "where did I put my API tokens?" without ever touching a
 * secret value:
 *   - every `secrets.NAME` referenced by `.github/workflows/*.yml`
 *   - which workflows consume each name
 *   - fallback chains (e.g. `DOPPLER_AGENT_TOKEN || DOPPLER_TOKEN || ...` or the
 *     repo-standard `ADMIN_GITHUB_TOKEN != '' && ADMIN_GITHUB_TOKEN || GITHUB_TOKEN`)
 *   - whether the Secrets Presence Ledger (secrets-backup-daily.yml) tracks it
 *
 * Single store: GitHub Actions repository secrets (Doppler is decommissioned —
 * see docs/SECRETS_MANAGEMENT.md). `GITHUB_TOKEN` is runner-provided, not a
 * stored secret, and is labeled as such.
 *
 * Usage: node scripts/secrets-map.js [--check]
 *   --check  exit 1 if docs/SECRETS_MAP.md is stale (for CI), without writing.
 *
 * Pure scan/render functions are exported for tests; IO lives in main().
 */

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const WORKFLOWS_DIR = path.join(ROOT, ".github/workflows");
const DOC_PATH = path.join(ROOT, "docs/SECRETS_MAP.md");
const LEDGER_WORKFLOW = path.join(WORKFLOWS_DIR, "secrets-backup-daily.yml");

const SECRET_REF = /secrets\.([A-Z][A-Z0-9_]*)/g;

/** Extract the set of secret names referenced in a workflow file's text. */
function extractSecrets(text) {
  const names = new Set();
  for (const m of text.matchAll(SECRET_REF)) names.add(m[1]);
  return names;
}

/**
 * Extract fallback chains: any `${{ ... }}` expression that references two or
 * more distinct secrets joined by `||` (covers both `A || B` and the
 * `A != '' && A || B` ternary-style pattern used across this repo).
 */
function extractFallbackChains(text) {
  const chains = [];
  for (const expr of text.matchAll(/\$\{\{([^}]*)\}\}/g)) {
    const body = expr[1];
    if (!body.includes("||")) continue;
    const ordered = [];
    for (const m of body.matchAll(SECRET_REF)) {
      if (!ordered.includes(m[1])) ordered.push(m[1]);
    }
    if (ordered.length >= 2) {
      const key = ordered.join(" → ");
      if (!chains.includes(key)) chains.push(key);
    }
  }
  return chains;
}

/**
 * Parse the presence-ledger NAMES list out of secrets-backup-daily.yml so the
 * map can flag which secrets the daily ledger watches (SSOT stays the
 * workflow — this just reads it).
 */
function extractLedgerNames(text) {
  const m = text.match(/NAMES = \[([^\]]*)\]/);
  if (!m) return [];
  return [...m[1].matchAll(/"([A-Z0-9_]+)"/g)].map((x) => x[1]);
}

/** Scan every workflow and build { name -> { workflows: [], chains: [] } }. */
function scanWorkflows(dir = WORKFLOWS_DIR) {
  const map = new Map();
  const files = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".yml") || f.endsWith(".yaml"))
    .sort();
  for (const file of files) {
    const text = fs.readFileSync(path.join(dir, file), "utf8");
    const names = extractSecrets(text);
    const chains = extractFallbackChains(text);
    for (const name of names) {
      if (!map.has(name)) map.set(name, { workflows: [], chains: [] });
      const entry = map.get(name);
      entry.workflows.push(file);
      for (const chain of chains) {
        if (
          chain.split(" → ").includes(name) &&
          !entry.chains.includes(chain)
        ) {
          entry.chains.push(chain);
        }
      }
    }
  }
  return map;
}

function locationFor(name) {
  if (name === "GITHUB_TOKEN")
    return "Runner-provided (built-in, never stored)";
  if (name.startsWith("DOPPLER_")) {
    return "GitHub → Settings → Secrets → Actions (**decommissioned** — delete after 7 quiet ledger days)";
  }
  return "GitHub → Settings → Secrets → Actions";
}

function renderMarkdown(map, ledgerNames = []) {
  const names = [...map.keys()].sort();
  const stored = names.filter((n) => n !== "GITHUB_TOKEN");
  const out = [];
  out.push(
    "<!-- generated by scripts/secrets-map.js from .github/workflows/*.yml — do not edit by hand -->",
  );
  out.push("# Secrets Map — names and locations ONLY (never values)");
  out.push("");
  out.push(
    "Every secret name referenced by the workflows, where it lives, which workflows " +
      "consume it, and its fallback chain. **Generated from `.github/workflows/*.yml`** — " +
      "run `npm run secrets:map` to regenerate, never hand-edit this file. Values live " +
      "in exactly ONE store: **GitHub Actions repository secrets** (plus your desktop " +
      "password manager — see `skills/credential-clerk/`). Doppler is decommissioned; " +
      "see `docs/SECRETS_MANAGEMENT.md`.",
  );
  out.push("");
  out.push(
    `**${stored.length}** stored secret names referenced · ` +
      `**${ledgerNames.length}** tracked by the daily presence ledger (\`docs/secrets-ledger.json\`).`,
  );
  out.push("");
  out.push("| Secret | Lives in | Ledger | Consumed by | Fallback chain |");
  out.push("| --- | --- | :---: | --- | --- |");
  for (const name of names) {
    const e = map.get(name);
    out.push(
      `| \`${name}\` | ${locationFor(name)} | ${ledgerNames.includes(name) ? "✅" : "—"} | ` +
        `${e.workflows.map((w) => `\`${w}\``).join(", ")} | ` +
        `${e.chains.length ? e.chains.map((c) => `\`${c}\``).join("<br>") : "—"} |`,
    );
  }
  out.push("");
  out.push("## Reading the map");
  out.push("");
  out.push(
    "- **Lives in** — the only write path is GitHub → repo Settings → Secrets and",
  );
  out.push(
    "  variables → Actions (`gh secret set NAME --repo midnghtsapphire/revvel-standards`).",
  );
  out.push(
    "- **Ledger** — ✅ means `secrets-backup-daily.yml` records daily presence +",
  );
  out.push(
    "  a peppered fingerprint in `docs/secrets-ledger.json` and files one",
  );
  out.push("  `[SECRET-MISSING]` issue if the name vanishes.");
  out.push(
    "- **Fallback chain** — the order workflows try names (`A → B` means A wins",
  );
  out.push(
    "  when set, else B). `DOPPLER_*` chains remain listed until the secrets are",
  );
  out.push("  deleted so the decommission is auditable.");
  out.push("");
  out.push(
    `*Last generated: ${new Date().toISOString().slice(0, 10)} from \`.github/workflows/\`.*`,
  );
  return `${out.join("\n")}\n`;
}

/** Compare ignoring the volatile "Last generated" date line. */
function normalize(md) {
  return md.replace(/^\*Last generated: \d{4}-\d{2}-\d{2}.*$/m, "");
}

function main(argv = process.argv.slice(2)) {
  const map = scanWorkflows();
  const ledgerNames = fs.existsSync(LEDGER_WORKFLOW)
    ? extractLedgerNames(fs.readFileSync(LEDGER_WORKFLOW, "utf8"))
    : [];
  const next = renderMarkdown(map, ledgerNames);
  if (argv.includes("--check")) {
    const current = fs.existsSync(DOC_PATH)
      ? fs.readFileSync(DOC_PATH, "utf8")
      : "";
    if (normalize(current) !== normalize(next)) {
      console.error(
        "❌ docs/SECRETS_MAP.md is stale — run `npm run secrets:map` and commit.",
      );
      process.exit(1);
    }
    console.log("✅ docs/SECRETS_MAP.md is up to date.");
    return;
  }
  fs.writeFileSync(DOC_PATH, next);
  console.log(
    `✅ wrote ${path.relative(ROOT, DOC_PATH)} (${map.size} secret names)`,
  );
}

module.exports = {
  extractSecrets,
  extractFallbackChains,
  extractLedgerNames,
  scanWorkflows,
  renderMarkdown,
  normalize,
};

if (require.main === module) main();
