#!/usr/bin/env bash
# Install the pre-review gate as a git pre-commit hook.
# Chains (does not replace) any pre-existing wr/memory JSONL hook.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

GATE=".pre-commit-hooks/pre-review-gate.sh"
JSONL_GATE=".pre-commit-hooks/wr-memory-jsonl.sh"  # optional / pre-existing
HOOK=".git/hooks/pre-commit"

chmod +x "$GATE" || true
[ -f "$JSONL_GATE" ] && chmod +x "$JSONL_GATE" || true

mkdir -p .git/hooks
if [ -f "$HOOK" ] && ! grep -q 'pre-review-gate' "$HOOK"; then
  cp "$HOOK" "$HOOK.backup.$(date +%s 2>/dev/null || echo bak)"
  echo "backed up existing $HOOK"
fi

cat > "$HOOK" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/setup-pre-review.sh — chains local gates.
set -e
REPO="$(git rev-parse --show-toplevel)"
[ -f "$REPO/.pre-commit-hooks/pre-review-gate.sh" ] && bash "$REPO/.pre-commit-hooks/pre-review-gate.sh"
[ -f "$REPO/.pre-commit-hooks/wr-memory-jsonl.sh" ] && bash "$REPO/.pre-commit-hooks/wr-memory-jsonl.sh"
exit 0
HOOK
chmod +x "$HOOK"
echo "installed: $HOOK"
