#!/usr/bin/env bash
# Install .git/hooks/pre-commit as a chain: pre-review-gate + existing JSONL gate.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

HOOK=".git/hooks/pre-commit"
GATE=".pre-commit-hooks/pre-review-gate.sh"
JSONL_GATE=".pre-commit-hooks/wr-memory-jsonl.sh"  # optional; chained if present

if [ ! -f "$GATE" ]; then
  echo "error: $GATE not found" >&2
  exit 1
fi
chmod +x "$GATE"

# Back up any existing unrelated hook
if [ -f "$HOOK" ] && ! grep -q 'pre-review-gate' "$HOOK" 2>/dev/null; then
  cp "$HOOK" "$HOOK.backup.$(date +%s)"
  echo "backed up existing pre-commit hook"
fi

cat > "$HOOK" <<'HOOK_EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/setup-pre-review.sh
# Chains pre-review gate then (if present) wr/memory JSONL gate.
set -e
REPO_ROOT="$(git rev-parse --show-toplevel)"
bash "$REPO_ROOT/.pre-commit-hooks/pre-review-gate.sh"
if [ -f "$REPO_ROOT/.pre-commit-hooks/validate-memory-jsonl.sh" ]; then
  bash "$REPO_ROOT/.pre-commit-hooks/validate-memory-jsonl.sh"
fi
HOOK_EOF

chmod +x "$HOOK"
echo "installed pre-commit hook chain at $HOOK"
