#!/usr/bin/env bash
# Install the pre-review commit gate as a git pre-commit hook.
# Chains (does not replace) any pre-existing wr/memory JSONL gate.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

HOOK_DIR=".git/hooks"
HOOK="$HOOK_DIR/pre-commit"
GATE=".pre-commit-hooks/pre-review-gate.sh"
JSONL_GATE=".pre-commit-hooks/validate-memory-jsonl.sh"

if [ ! -f "$GATE" ]; then
  echo "error: $GATE not found" >&2
  exit 1
fi
chmod +x "$GATE"

mkdir -p "$HOOK_DIR"

# Back up an existing, unrelated pre-commit hook (once).
if [ -f "$HOOK" ] && ! grep -q 'pre-review-gate.sh' "$HOOK" 2>/dev/null; then
  cp "$HOOK" "$HOOK.backup.$(date +%s)"
  echo "backed up existing hook to $HOOK.backup.*"
fi

cat > "$HOOK" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/setup-pre-review.sh — chained hook.
set -e
REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# 1. Pre-review gate (markdown/YAML/JSON auto-fix + validation)
if [ -f .pre-commit-hooks/pre-review-gate.sh ]; then
  bash .pre-commit-hooks/pre-review-gate.sh || exit $?
fi

# 2. JSONL / memory gate (if present)
if [ -f .pre-commit-hooks/jsonl-memory-gate.sh ]; then
  bash .pre-commit-hooks/jsonl-memory-gate.sh || exit $?
fi

exit 0
EOF

chmod +x "$HOOK"
echo "installed pre-commit hook at $HOOK"
echo "  → chains: $GATE"
[ -f "$JSONL_GATE" ] && echo "  → chains: $JSONL_GATE"
echo "done."
