#!/bin/bash
# Sync BOM — Regenerates docs/_MASTER_BOM.md from individual project BOM files
# Usage: ./scripts/sync-bom.sh
# Run from the revvel-standards repo root

set -euo pipefail

DOCS_DIR="$(dirname "$0")/../docs"
MASTER_BOM="$DOCS_DIR/_MASTER_BOM.md"
TODAY=$(date +"%Y-%m-%d")

echo "======================================"
echo "  Revvel BOM Sync"
echo "======================================"
echo ""

# Find all project BOM files
BOM_FILES=()
while IFS= read -r -d '' f; do
  BOM_FILES+=("$f")
done < <(find "$DOCS_DIR" -name "BOM.md" -not -path "$DOCS_DIR/BOM.md" -print0 | sort -z)

if [ ${#BOM_FILES[@]} -eq 0 ]; then
  echo "No BOM.md files found in $DOCS_DIR"
  exit 1
fi

echo "Found ${#BOM_FILES[@]} project BOM files:"
for f in "${BOM_FILES[@]}"; do
  echo "  - $f"
done
echo ""

# -------------------------------------------------------------------------
# Generate master BOM header
# -------------------------------------------------------------------------
cat > "$MASTER_BOM" << EOF
# Master Bill of Materials — All Revvel Projects

> **Note:** This file was auto-generated by \`scripts/sync-bom.sh\` on $TODAY.
> To regenerate: \`bash scripts/sync-bom.sh\` from the revvel-standards repo root.

**Last Regenerated:** $TODAY

---

## Outstanding Purchases by Priority

The following items are marked ❌ "Not purchased" across all project BOMs, sorted by priority.

EOF

# -------------------------------------------------------------------------
# Extract and categorize "Purchase Needed" rows
# -------------------------------------------------------------------------

# Collect all ❌ rows from Purchase Needed sections
P0_ROWS=()
P1_ROWS=()
P2_ROWS=()

for bom_file in "${BOM_FILES[@]}"; do
  # Get project name from directory
  project_dir=$(basename "$(dirname "$bom_file")")
  project_name=$(echo "$project_dir" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1')

  # Extract lines with ❌ from the Purchase Needed table
  in_purchase_section=false
  while IFS= read -r line; do
    if echo "$line" | grep -q "## Purchase Needed"; then
      in_purchase_section=true
      continue
    fi
    if $in_purchase_section && echo "$line" | grep -q "^## "; then
      in_purchase_section=false
    fi
    if $in_purchase_section && echo "$line" | grep -q "❌"; then
      # Extract priority from the row (P0/P1/P2)
      priority=$(echo "$line" | grep -oE 'P[012]' | head -1)
      row="| $project_name $line"
      case "$priority" in
        P0) P0_ROWS+=("$row") ;;
        P1) P1_ROWS+=("$row") ;;
        P2) P2_ROWS+=("$row") ;;
        *)  P2_ROWS+=("$row") ;; # Default to P2 if no priority found
      esac
    fi
  done < "$bom_file"
done

# Write P0 section
echo "### P0 — Do Immediately" >> "$MASTER_BOM"
echo "" >> "$MASTER_BOM"
echo "| Project | Item | Provider | Est. Cost | Priority | Status |" >> "$MASTER_BOM"
echo "|---|---|---|---|---|---|" >> "$MASTER_BOM"
if [ ${#P0_ROWS[@]} -gt 0 ]; then
  for row in "${P0_ROWS[@]}"; do
    echo "$row" >> "$MASTER_BOM"
  done
else
  echo "| — | No P0 items outstanding | — | — | — | — |" >> "$MASTER_BOM"
fi

echo "" >> "$MASTER_BOM"
echo "### P1 — Do Soon" >> "$MASTER_BOM"
echo "" >> "$MASTER_BOM"
echo "| Project | Item | Provider | Est. Cost | Priority | Status |" >> "$MASTER_BOM"
echo "|---|---|---|---|---|---|" >> "$MASTER_BOM"
if [ ${#P1_ROWS[@]} -gt 0 ]; then
  for row in "${P1_ROWS[@]}"; do
    echo "$row" >> "$MASTER_BOM"
  done
else
  echo "| — | No P1 items outstanding | — | — | — | — |" >> "$MASTER_BOM"
fi

echo "" >> "$MASTER_BOM"
echo "### P2 — Do When Ready for Stores" >> "$MASTER_BOM"
echo "" >> "$MASTER_BOM"
echo "| Project | Item | Provider | Est. Cost | Priority | Status |" >> "$MASTER_BOM"
echo "|---|---|---|---|---|---|" >> "$MASTER_BOM"
if [ ${#P2_ROWS[@]} -gt 0 ]; then
  for row in "${P2_ROWS[@]}"; do
    echo "$row" >> "$MASTER_BOM"
  done
else
  echo "| — | No P2 items outstanding | — | — | — | — |" >> "$MASTER_BOM"
fi

# -------------------------------------------------------------------------
# Footer with project links
# -------------------------------------------------------------------------
cat >> "$MASTER_BOM" << EOF

---

## Project BOM Files

EOF

for bom_file in "${BOM_FILES[@]}"; do
  project_dir=$(basename "$(dirname "$bom_file")")
  project_name=$(echo "$project_dir" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1')
  rel_path=$(echo "$bom_file" | sed "s|$DOCS_DIR/||")
  echo "- [$project_name BOM]($rel_path)" >> "$MASTER_BOM"
done

echo "" >> "$MASTER_BOM"
echo "---" >> "$MASTER_BOM"
echo "" >> "$MASTER_BOM"
echo "*Auto-generated by \`scripts/sync-bom.sh\` — Do not edit manually.*" >> "$MASTER_BOM"

echo "✅ Generated: $MASTER_BOM"
echo ""

# -------------------------------------------------------------------------
# Preserve manually-maintained Universal Tool Suggestions section
# -------------------------------------------------------------------------
# If a MASTER_BOM_APPENDIX.md exists, append it after the auto-generated content.
APPENDIX="$DOCS_DIR/_MASTER_BOM_APPENDIX.md"
if [ -f "$APPENDIX" ]; then
  echo "Appending universal tool suggestions from $APPENDIX…"
  cat "$APPENDIX" >> "$MASTER_BOM"
  echo "✅ Appendix appended."
fi

echo ""
echo "Done!"
