name: Mergify Merge-Queue Labels Copier
on:
  pull_request_target:
    types:
      - opened
permissions:
  contents: read
  pull-requests: write
jobs:
  mergify-merge-queue-labels-copier:
    name: Copy Labels to Merge-Queue PR
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.head.ref, 'mergify/merge-queue/') && github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Copy labels to merge-queue PR
        uses: Mergifyio/gha-mergify-merge-queue-labels-copier@v6
        with:
          labels: docker
          additional-labels: merge-queue-pr
          token: ${{ github.token }}
    timeout-minutes: 15
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
