name: Morty Post Mortems

on:
  push:
    branches: [main]
    paths:
      - 'post-mortems/**'
      - '.github/workflows/morty-post-mortems.yml'
  pull_request:
    branches: [main]
    paths:
      - 'post-mortems/**'
      - '.github/workflows/morty-post-mortems.yml'
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  morty-post-mortems:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Morty Post Mortems
        uses: mentimeter/morty@d0db9f4556af12dc142f6af5e2f3d88dbdd3b2a9 # v1.2.1
        with:
          token: ${{ github.token }}
