---
name: Super-Linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  super-linter:
    name: Super-Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      issues: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-Linter
        uses: super-linter/super-linter@v8.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: wr/issues/.*
